package dev.mrk.meshingress.security;

import dev.mrk.aegis.ResourceLimitPolicy;
import dev.mrk.meshingress.api.McpCallContext;
import dev.mrk.meshingress.config.MeshingressProperties;
import dev.mrk.meshingress.mcp.jsonrpc.JsonRpcErrorCodes;
import dev.mrk.meshingress.mcp.jsonrpc.JsonRpcException;
import dev.mrk.meshingress.security.management.JdbcProfileStore;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.node.ObjectNode;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

/** Request-time profile limits. Only verified principal data selects a usage key. */
@Service
public final class ProfileLimitService {
    private static final String USAGE_TABLE = "meshingress.security_profile_limit_usage";
    private static final String EVENT_TABLE = "meshingress.security_profile_limit_events";
    private final MeshingressProperties properties;
    private final JdbcProfileStore profiles;
    private final JdbcTemplate jdbc;
    private final ObjectMapper objectMapper;
    private final Map<String, AtomicInteger> concurrent = new ConcurrentHashMap<>();

    public ProfileLimitService(MeshingressProperties properties, JdbcProfileStore profiles, JdbcTemplate jdbc, ObjectMapper objectMapper) {
        this.properties = properties; this.profiles = profiles; this.jdbc = jdbc; this.objectMapper = objectMapper;
        jdbc.execute("create schema if not exists meshingress");
        jdbc.execute("create table if not exists " + USAGE_TABLE + " (event_id bigint generated by default as identity primary key, occurred_at timestamp with time zone not null, profile_key varchar(128) not null, metric varchar(64) not null, tool_name varchar(512))");
        jdbc.execute("create index if not exists security_profile_limit_usage_idx on " + USAGE_TABLE + " (profile_key, metric, occurred_at)");
        jdbc.execute("create table if not exists " + EVENT_TABLE + " (event_id bigint generated by default as identity primary key, occurred_at timestamp with time zone not null, profile_key varchar(128) not null, metric varchar(64) not null, outcome varchar(32) not null, detail varchar(512), request_id varchar(255))");
    }

    public Reservation reserveRequest(McpCallContext context) { return reserve(context, null, "requests", effective(context).requests(), false); }
    public Reservation reserveToolExecution(McpCallContext context, String toolName) { return reserve(context, toolName, "toolExecutions", effective(context).toolExecutions(), true); }

    public ResourceLimitPolicy effective(McpCallContext context) {
        MeshingressProperties.Security.Limits configured = properties.security().limits();
        ResourceLimitPolicy base = new ResourceLimitPolicy(ResourceLimitPolicy.CURRENT_SCHEMA_VERSION,
                configured.enabled() ? ResourceLimitPolicy.Enforcement.ENABLED : ResourceLimitPolicy.Enforcement.DISABLED,
                configured.requestsPerWindow() == 0 ? ResourceLimitPolicy.LimitValue.unlimited() : ResourceLimitPolicy.LimitValue.limited(configured.requestsPerWindow(), configured.requestWindow().toSeconds()),
                configured.toolExecutionsPerWindow() == 0 ? ResourceLimitPolicy.LimitValue.unlimited() : ResourceLimitPolicy.LimitValue.limited(configured.toolExecutionsPerWindow(), configured.toolExecutionWindow().toSeconds()),
                configured.maxConcurrentCalls() == 0 ? ResourceLimitPolicy.LimitValue.unlimited() : ResourceLimitPolicy.LimitValue.limited(configured.maxConcurrentCalls(), 0),
                ResourceLimitPolicy.LimitValue.unlimited());
        String profileId = context == null ? "" : context.principal().profileId();
        if (profileId == null || profileId.isBlank()) return base;
        try {
            return profiles.find(UUID.fromString(profileId)).map(snapshot -> snapshot.profile().limitPolicy().resolveAgainst(base)).orElse(base);
        } catch (IllegalArgumentException ignored) { return base; }
    }

    public java.util.List<UsageEvent> usage(String profileId, int limit) {
        String key = profileKey(profileId, "", "");
        return jdbc.query("select occurred_at, metric, tool_name from " + USAGE_TABLE + " where profile_key = ? order by occurred_at desc limit ?",
                (row, number) -> new UsageEvent(row.getTimestamp(1).toInstant(), row.getString(2), row.getString(3)), key, limit);
    }

    private synchronized Reservation reserve(McpCallContext context, String toolName, String metric, ResourceLimitPolicy.LimitValue rate, boolean useConcurrency) {
        ResourceLimitPolicy policy = effective(context);
        String key = profileKey(context == null ? "" : context.principal().profileId(), context == null ? "" : context.principal().issuer(), context == null ? "" : context.principal().subject());
        boolean enforce = policy.enforcement() == ResourceLimitPolicy.Enforcement.ENABLED;
        boolean meter = enforce || properties.security().limits().recordUsage();
        if (enforce && rate.mode() == ResourceLimitPolicy.Mode.LIMITED) {
            Instant cutoff = Instant.now().minusSeconds(rate.windowSeconds());
            Long count = jdbc.queryForObject("select count(*) from " + USAGE_TABLE + " where profile_key = ? and metric = ? and occurred_at >= ?", Long.class, key, metric, cutoff);
            if (count != null && count >= rate.limit()) throw denied(key, metric, "rolling-window quota", context, retryAfter(rate.windowSeconds()));
        }
        boolean acquired = false;
        if (useConcurrency && enforce && policy.concurrentCalls().mode() == ResourceLimitPolicy.Mode.LIMITED) {
            AtomicInteger count = concurrent.computeIfAbsent(key, ignored -> new AtomicInteger());
            if (count.incrementAndGet() > policy.concurrentCalls().limit()) {
                count.decrementAndGet();
                throw denied(key, "concurrentCalls", "concurrency quota", context, 1);
            }
            acquired = true;
        }
        if (meter) jdbc.update("insert into " + USAGE_TABLE + " (occurred_at, profile_key, metric, tool_name) values (?, ?, ?, ?)", Instant.now(), key, metric, toolName);
        return new Reservation(key, acquired);
    }

    private JsonRpcException denied(String key, String metric, String detail, McpCallContext context, long retryAfterSeconds) {
        jdbc.update("insert into " + EVENT_TABLE + " (occurred_at, profile_key, metric, outcome, detail, request_id) values (?, ?, ?, ?, ?, ?)", Instant.now(), key, metric, "DENIED", detail, context == null ? "" : context.requestId());
        ObjectNode data = objectMapper.createObjectNode(); data.put("reason", "PROFILE_LIMIT_EXCEEDED"); data.put("metric", metric); data.put("retryAfterSeconds", retryAfterSeconds);
        return new JsonRpcException(JsonRpcErrorCodes.RATE_LIMITED, "Profile limit exceeded.", data);
    }

    private static long retryAfter(long windowSeconds) { return Math.max(1, windowSeconds); }
    private static String profileKey(String profileId, String issuer, String subject) {
        String material = profileId != null && !profileId.isBlank() ? "profile:" + profileId : "identity:" + issuer + "\u0000" + subject;
        try { return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(material.getBytes(StandardCharsets.UTF_8))); }
        catch (java.security.NoSuchAlgorithmException exception) { throw new IllegalStateException("SHA-256 is unavailable", exception); }
    }

    public final class Reservation implements AutoCloseable {
        private final String key; private final boolean acquired; private boolean closed;
        private Reservation(String key, boolean acquired) { this.key = key; this.acquired = acquired; }
        @Override public void close() {
            if (!closed && acquired) concurrent.getOrDefault(key, new AtomicInteger()).decrementAndGet();
            closed = true;
        }
    }
    public record UsageEvent(Instant occurredAt, String metric, String toolName) { }
}
