package dev.mrk.meshingress.security.management;

import dev.mrk.aegis.AuthProfile;
import dev.mrk.aegis.AuthenticatedIdentity;
import dev.mrk.aegis.CredentialBinding;
import dev.mrk.aegis.ProfileDraft;
import dev.mrk.aegis.ProfileQuery;
import dev.mrk.aegis.ProfileRevisionConflictException;
import dev.mrk.aegis.ProfileService;
import dev.mrk.aegis.ProfileSnapshot;
import dev.mrk.aegis.ProfileStatus;
import dev.mrk.aegis.ResourceLimitPolicy;
import dev.mrk.meshingress.api.McpCallContext;
import dev.mrk.meshingress.mcp.jsonrpc.JsonRpcErrorCodes;
import dev.mrk.meshingress.mcp.jsonrpc.JsonRpcException;
import dev.mrk.meshingress.security.McpAccessPolicyService;
import dev.mrk.meshingress.security.ProfileLimitService;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.node.ArrayNode;
import tools.jackson.databind.node.ObjectNode;

import java.time.Instant;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

/** Route-facing adapter: tenant checks, safe DTO conversion, and management audit events. */
@Service
public final class SecurityManagementService {
    private static final String AUDIT_TABLE = "meshingress.security_management_audit";
    private final ProfileService profiles;
    private final ToolPolicyService policies;
    private final McpAccessPolicyService access;
    private final ObjectMapper objectMapper;
    private final JdbcTemplate jdbc;
    private final ProfileLimitService limits;

    public SecurityManagementService(JdbcProfileStore store, ToolPolicyService policies, McpAccessPolicyService access, ObjectMapper objectMapper, JdbcTemplate jdbc, ProfileLimitService limits) {
        this.profiles = new ProfileService(store);
        this.policies = policies;
        this.access = access;
        this.objectMapper = objectMapper;
        this.jdbc = jdbc;
        this.limits = limits;
        jdbc.execute("create schema if not exists meshingress");
        jdbc.execute("create table if not exists " + AUDIT_TABLE + " (event_id bigint generated by default as identity primary key, occurred_at timestamp with time zone not null, tenant_id varchar(255) not null, actor varchar(255) not null, action varchar(128) not null, resource_id varchar(255) not null, revision bigint, request_id varchar(255))");
    }

    public ObjectNode whoami(McpCallContext context) {
        access.requireVerifiedIdentity(context);
        ObjectNode result = objectMapper.createObjectNode();
        result.set("principal", objectMapper.valueToTree(context.principal()));
        return result;
    }

    public ObjectNode profilesList(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context);
        int limit = boundedLimit(params.path("limit").asInt(100));
        Set<ProfileStatus> statuses = enumSet(params.path("statuses"), ProfileStatus.class, "statuses");
        ArrayNode values = objectMapper.createArrayNode();
        profiles.list(new ProfileQuery(statuses, ProfileQuery.MAXIMUM_LIMIT)).stream()
                .filter(snapshot -> snapshot.profile().tenantId().equals(tenant)).limit(limit)
                .forEach(snapshot -> values.add(profileJson(snapshot)));
        ObjectNode result = objectMapper.createObjectNode(); result.set("profiles", values); return result;
    }

    public ObjectNode profilesGet(McpCallContext context, JsonNode params) { return profileResult(requireOwned(managerTenant(context), profileId(params))); }

    public ObjectNode profilesCreate(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context); requireObject(params, "params"); rejectRawCredentialMaterial(params);
        ObjectNode draftNode = ((ObjectNode) params).deepCopy(); draftNode.put("tenantId", tenant);
        ProfileSnapshot created = profiles.create(objectMapper.convertValue(draftNode, ProfileDraft.class));
        audit(context, tenant, "profile.create", created.profile().profileId().toString(), created.revision());
        return profileResult(created);
    }

    public ObjectNode profilesUpdate(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context); ProfileSnapshot current = requireOwned(tenant, profileId(params));
        long expected = expectedRevision(params); String displayName = params.has("displayName") && !params.path("displayName").isNull()
                ? text(params, "displayName") : current.profile().metadata().displayName();
        Map<String, String> labels = params.has("labels") && !params.path("labels").isNull()
                ? objectMapper.convertValue(params.path("labels"), objectMapper.getTypeFactory().constructMapType(Map.class, String.class, String.class))
                : current.profile().metadata().labels();
        ProfileSnapshot updated = mutation(() -> profiles.updateMetadata(current.profile().profileId(), expected, displayName, labels));
        audit(context, tenant, "profile.update", updated.profile().profileId().toString(), updated.revision()); return profileResult(updated);
    }

    public ObjectNode profilesActivate(McpCallContext context, JsonNode params) { return status(context, params, "profile.activate", (id, revision) -> profiles.activate(id, revision)); }
    public ObjectNode profilesDisable(McpCallContext context, JsonNode params) { return status(context, params, "profile.disable", (id, revision) -> profiles.disable(id, revision)); }
    public ObjectNode profilesRevoke(McpCallContext context, JsonNode params) { return status(context, params, "profile.revoke", (id, revision) -> profiles.revoke(id, revision)); }

    public ObjectNode identitiesLink(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context); ProfileSnapshot current = requireOwned(tenant, profileId(params));
        AuthenticatedIdentity identity = objectMapper.convertValue(requireField(params, "identity"), AuthenticatedIdentity.class);
        ProfileSnapshot updated = mutation(() -> profiles.linkIdentity(current.profile().profileId(), expectedRevision(params), identity));
        audit(context, tenant, "profile.identity.link", current.profile().profileId().toString(), updated.revision()); return profileResult(updated);
    }

    public ObjectNode identitiesUnlink(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context); ProfileSnapshot current = requireOwned(tenant, profileId(params));
        ProfileSnapshot updated = mutation(() -> profiles.unlinkIdentity(current.profile().profileId(), expectedRevision(params), text(params, "identityId")));
        audit(context, tenant, "profile.identity.unlink", current.profile().profileId().toString(), updated.revision()); return profileResult(updated);
    }

    public ObjectNode credentialsBind(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context); rejectRawCredentialMaterial(params); ProfileSnapshot current = requireOwned(tenant, profileId(params));
        CredentialBinding binding = objectMapper.convertValue(requireField(params, "binding"), CredentialBinding.class);
        ProfileSnapshot updated = mutation(() -> profiles.bindCredential(current.profile().profileId(), expectedRevision(params), binding));
        audit(context, tenant, "profile.credential.bind", current.profile().profileId().toString(), updated.revision()); return profileResult(updated);
    }

    public ObjectNode credentialsReplace(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context); rejectRawCredentialMaterial(params); ProfileSnapshot current = requireOwned(tenant, profileId(params));
        CredentialBinding binding = objectMapper.convertValue(requireField(params, "binding"), CredentialBinding.class);
        ProfileSnapshot updated = mutation(() -> profiles.replaceCredential(current.profile().profileId(), expectedRevision(params), text(params, "bindingId"), binding));
        audit(context, tenant, "profile.credential.replace", current.profile().profileId().toString(), updated.revision()); return profileResult(updated);
    }

    public ObjectNode credentialsRevoke(McpCallContext context, JsonNode params) { return credentialState(context, params, "profile.credential.revoke", true); }
    public ObjectNode credentialsUnbind(McpCallContext context, JsonNode params) { return credentialState(context, params, "profile.credential.unbind", false); }

    public ObjectNode credentialBindingsList(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context); ArrayNode values = objectMapper.createArrayNode();
        for (ProfileSnapshot snapshot : profiles.list(new ProfileQuery(Set.of(), ProfileQuery.MAXIMUM_LIMIT))) {
            if (!snapshot.profile().tenantId().equals(tenant)) continue;
            for (CredentialBinding binding : snapshot.profile().credentialBindings()) {
                ObjectNode value = objectMapper.createObjectNode(); value.put("profileId", snapshot.profile().profileId().toString()); value.put("profileRevision", snapshot.revision()); value.set("binding", objectMapper.valueToTree(binding)); values.add(value);
            }
        }
        ObjectNode result = objectMapper.createObjectNode(); result.set("credentialBindings", values); return result;
    }

    public ObjectNode credentialBindingsGet(McpCallContext context, JsonNode params) {
        ProfileSnapshot profile = requireOwned(managerTenant(context), profileId(params)); String bindingId = text(params, "bindingId");
        CredentialBinding binding = profile.profile().credentialBindings().stream().filter(value -> value.id().equals(bindingId)).findFirst()
                .orElseThrow(() -> invalid("unknown credential binding: " + bindingId));
        ObjectNode result = objectMapper.createObjectNode(); result.put("profileId", profile.profile().profileId().toString()); result.put("profileRevision", profile.revision()); result.set("binding", objectMapper.valueToTree(binding)); return result;
    }

    public ObjectNode profileLimitsGet(McpCallContext context, JsonNode params) {
        ProfileSnapshot profile = requireOwned(managerTenant(context), profileId(params));
        ObjectNode result = objectMapper.createObjectNode();
        result.put("profileId", profile.profile().profileId().toString());
        result.put("profileRevision", profile.revision());
        result.set("limitPolicy", objectMapper.valueToTree(profile.profile().limitPolicy()));
        result.set("effectiveLimitPolicy", objectMapper.valueToTree(limits.effective(new McpCallContext(null, context.principal().withProfile(profile.profile().profileId().toString(), profile.profile().tenantId()), null, null, null))));
        return result;
    }

    public ObjectNode profileLimitsUpdate(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context); ProfileSnapshot current = requireOwned(tenant, profileId(params));
        ResourceLimitPolicy policy = objectMapper.convertValue(requireField(params, "limitPolicy"), ResourceLimitPolicy.class);
        ProfileSnapshot updated = mutation(() -> profiles.updateLimitPolicy(current.profile().profileId(), expectedRevision(params), policy));
        audit(context, tenant, "profile.limits.update", current.profile().profileId().toString(), updated.revision());
        return profileLimitsGet(context, objectMapper.createObjectNode().put("profileId", current.profile().profileId().toString()));
    }

    public ObjectNode profileUsageList(McpCallContext context, JsonNode params) {
        ProfileSnapshot profile = requireOwned(managerTenant(context), profileId(params));
        ObjectNode result = objectMapper.createObjectNode();
        result.put("profileId", profile.profile().profileId().toString());
        result.set("usage", objectMapper.valueToTree(limits.usage(profile.profile().profileId().toString(), boundedLimit(params.path("limit").asInt(100)))));
        return result;
    }

    public ObjectNode policiesList(McpCallContext context) { return policiesResult("toolPolicies", policies.list(managerTenant(context))); }
    public ObjectNode policiesGet(McpCallContext context, JsonNode params) { return policyResult(policy(managerTenant(context), policyId(params))); }

    public ObjectNode policiesCreate(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context); ToolPolicyService.PolicySnapshot created = policies.create(tenant, text(params, "toolName"), effect(params), grants(params), nonNegative(params, "priority"), params.path("enabled").asBoolean(true));
        audit(context, tenant, "tool-policy.create", created.policy().policyId().toString(), created.revision()); return policyResult(created);
    }

    public ObjectNode policiesUpdate(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context); UUID id = policyId(params); ToolPolicyService.PolicySnapshot updated = policyMutation(() -> policies.update(tenant, id, expectedRevision(params), effect(params), grants(params), nonNegative(params, "priority"), params.path("enabled").asBoolean(true)));
        audit(context, tenant, "tool-policy.update", id.toString(), updated.revision()); return policyResult(updated);
    }

    public ObjectNode policiesDelete(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context); UUID id = policyId(params); policyMutation(() -> { policies.delete(tenant, id, expectedRevision(params)); return null; });
        audit(context, tenant, "tool-policy.delete", id.toString(), expectedRevision(params)); ObjectNode result = objectMapper.createObjectNode(); result.put("deleted", true); result.put("policyId", id.toString()); return result;
    }

    public ObjectNode policiesEvaluate(McpCallContext context, JsonNode params) {
        String tenant = managerTenant(context); String toolName = text(params, "toolName");
        ToolPolicyService.ToolPolicyDecision decision = policies.evaluate(toolName, context.principal());
        ObjectNode result = objectMapper.createObjectNode(); result.put("tenantId", tenant); result.put("toolName", toolName); result.put("allowed", decision.allowed()); result.put("reason", decision.reason()); result.set("matchedPolicyIds", objectMapper.valueToTree(decision.matchedPolicyIds())); return result;
    }

    private ObjectNode status(McpCallContext context, JsonNode params, String action, StatusMutation mutation) {
        String tenant = managerTenant(context); ProfileSnapshot current = requireOwned(tenant, profileId(params)); ProfileSnapshot updated = mutation.apply(current.profile().profileId(), expectedRevision(params)); audit(context, tenant, action, current.profile().profileId().toString(), updated.revision()); return profileResult(updated);
    }
    private ObjectNode credentialState(McpCallContext context, JsonNode params, String action, boolean revoke) {
        String tenant = managerTenant(context); ProfileSnapshot current = requireOwned(tenant, profileId(params)); ProfileSnapshot updated = mutation(() -> revoke ? profiles.revokeCredential(current.profile().profileId(), expectedRevision(params), text(params, "bindingId")) : profiles.unbindCredential(current.profile().profileId(), expectedRevision(params), text(params, "bindingId"))); audit(context, tenant, action, current.profile().profileId().toString(), updated.revision()); return profileResult(updated);
    }
    private ProfileSnapshot requireOwned(String tenant, UUID id) {
        ProfileSnapshot snapshot = profiles.get(id); if (!snapshot.profile().tenantId().equals(tenant)) throw new JsonRpcException(JsonRpcErrorCodes.FORBIDDEN, "Profile is not in the caller tenant."); return snapshot;
    }
    private ToolPolicyService.PolicySnapshot policy(String tenant, UUID id) { return policies.find(tenant, id).orElseThrow(() -> invalid("unknown tool policy: " + id)); }
    private String managerTenant(McpCallContext context) { access.requireSecurityManager(context); String tenant = context.principal().tenantId(); if (tenant == null || tenant.isBlank()) throw new JsonRpcException(JsonRpcErrorCodes.FORBIDDEN, "Verified identity does not include a tenant claim."); return tenant; }
    private ObjectNode profileResult(ProfileSnapshot snapshot) { ObjectNode result = objectMapper.createObjectNode(); result.set("profile", profileJson(snapshot)); return result; }
    private ObjectNode profileJson(ProfileSnapshot snapshot) { ObjectNode result = objectMapper.createObjectNode(); result.put("revision", snapshot.revision()); result.set("profile", objectMapper.valueToTree(snapshot.profile())); return result; }
    private ObjectNode policyResult(ToolPolicyService.PolicySnapshot snapshot) { ObjectNode result = objectMapper.createObjectNode(); result.set("toolPolicy", objectMapper.valueToTree(snapshot)); return result; }
    private ObjectNode policiesResult(String name, List<ToolPolicyService.PolicySnapshot> snapshots) { ObjectNode result = objectMapper.createObjectNode(); result.set(name, objectMapper.valueToTree(snapshots)); return result; }
    private void audit(McpCallContext context, String tenant, String action, String resource, Long revision) { jdbc.update("insert into " + AUDIT_TABLE + " (occurred_at, tenant_id, actor, action, resource_id, revision, request_id) values (?, ?, ?, ?, ?, ?, ?)", Instant.now(), tenant, context.principal().subject(), action, resource, revision, context.requestId()); }
    private UUID profileId(JsonNode params) { return uuid(text(params, "profileId"), "profileId"); }
    private UUID policyId(JsonNode params) { return uuid(text(params, "policyId"), "policyId"); }
    private UUID uuid(String value, String field) { try { return UUID.fromString(value); } catch (IllegalArgumentException exception) { throw invalid(field + " must be a UUID"); } }
    private long expectedRevision(JsonNode params) { JsonNode value = requireField(params, "expectedRevision"); if (!value.canConvertToLong() || value.asLong() < 0) throw invalid("expectedRevision must be a non-negative integer"); return value.asLong(); }
    private int nonNegative(JsonNode params, String field) { JsonNode value = requireField(params, field); if (!value.canConvertToInt() || value.asInt() < 0) throw invalid(field + " must be a non-negative integer"); return value.asInt(); }
    private String text(JsonNode params, String field) { JsonNode value = requireField(params, field); if (!value.isTextual() || value.asString().isBlank()) throw invalid(field + " must be a non-blank string"); return value.asString().trim(); }
    private JsonNode requireField(JsonNode params, String field) { requireObject(params, "params"); JsonNode value = params.get(field); if (value == null || value.isNull()) throw invalid(field + " is required"); return value; }
    private void requireObject(JsonNode value, String name) { if (value == null || !value.isObject()) throw invalid(name + " must be an object"); }
    private int boundedLimit(int value) { if (value < 1 || value > ProfileQuery.MAXIMUM_LIMIT) throw invalid("limit must be between 1 and " + ProfileQuery.MAXIMUM_LIMIT); return value; }
    private <E extends Enum<E>> Set<E> enumSet(JsonNode node, Class<E> type, String field) { if (node == null || node.isMissingNode() || node.isNull()) return Set.of(); if (!node.isArray()) throw invalid(field + " must be an array"); Set<E> values = new LinkedHashSet<>(); for (JsonNode value : node) { try { values.add(Enum.valueOf(type, value.asString(""))); } catch (IllegalArgumentException exception) { throw invalid("invalid " + field + " value"); } } return Set.copyOf(values); }
    private StoredToolPolicy.Effect effect(JsonNode params) { try { return StoredToolPolicy.Effect.valueOf(text(params, "effect").toUpperCase(java.util.Locale.ROOT)); } catch (IllegalArgumentException exception) { throw invalid("effect must be ALLOW or DENY"); } }
    private Set<String> grants(JsonNode params) { JsonNode node = requireField(params, "requiredGrants"); if (!node.isArray()) throw invalid("requiredGrants must be an array"); Set<String> values = new LinkedHashSet<>(); for (JsonNode value : node) { if (!value.isTextual() || value.asString().isBlank()) throw invalid("requiredGrants entries must be non-blank strings"); values.add(value.asString()); } return Set.copyOf(values); }
    private void rejectRawCredentialMaterial(JsonNode node) { if (node == null) return; if (node.isObject()) node.properties().forEach(entry -> { String key = entry.getKey().toLowerCase(java.util.Locale.ROOT); if (!key.equals("secretreference") && (key.contains("token") || key.contains("password") || key.contains("privatekey") || key.equals("secret") || key.contains("apikey") || key.contains("authorization"))) throw invalid("raw credential material is not accepted"); rejectRawCredentialMaterial(entry.getValue()); }); else if (node.isArray()) for (JsonNode value : node) rejectRawCredentialMaterial(value); }
    private ProfileSnapshot mutation(ProfileMutation operation) { try { return operation.apply(); } catch (ProfileRevisionConflictException exception) { throw new JsonRpcException(JsonRpcErrorCodes.REVISION_CONFLICT, exception.getMessage()); } catch (IllegalArgumentException | IllegalStateException exception) { throw invalid(exception.getMessage()); } }
    private <T> T policyMutation(PolicyMutation<T> operation) { try { return operation.apply(); } catch (ToolPolicyService.PolicyRevisionConflictException exception) { throw new JsonRpcException(JsonRpcErrorCodes.REVISION_CONFLICT, exception.getMessage()); } catch (IllegalArgumentException exception) { throw invalid(exception.getMessage()); } }
    private JsonRpcException invalid(String message) { return new JsonRpcException(JsonRpcErrorCodes.INVALID_PARAMS, message); }
    @FunctionalInterface private interface ProfileMutation { ProfileSnapshot apply(); }
    @FunctionalInterface private interface StatusMutation { ProfileSnapshot apply(UUID id, long revision); }
    @FunctionalInterface private interface PolicyMutation<T> { T apply(); }
}
