<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.mrk.meshingress</groupId>
        <artifactId>meshingress</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>meshingress-server</artifactId>
    <name>meshingress-server</name>
    <description>Meshingress Spring Boot MCP server</description>

    <dependencies>
        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-tool-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-tool-annotations</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-route-framework</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-tool-framework</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-tool-runtime-loader</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-tool-api-manifest</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-artifact-model</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-artifact-storage</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-artifact-security</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-artifact-publication</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-artifact-scope-scanner</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-tool-bundle</artifactId>
            <version>${project.version}</version>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jackson</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>3.0.3</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>dev.mrk.meshingress</groupId>
            <artifactId>meshingress-config</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>

    <build>
        <finalName>meshingress</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>repackage</id>
                        <configuration>
                            <skip>false</skip>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <skip>false</skip>
                    <mainClass>dev.mrk.meshingress.MeshingressApplication</mainClass>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
