meshingress.mcp.auth.stub.enabled=true
meshingress.mcp.auth.stub.access-token=access-5285ae81675d4079b6ef454d5ec7228d
meshingress.mcp.auth.stub.secret-key=secret-b051c22af9874fc89ce5be1ff21bc183
meshingress.mcp.auth.stub.auth-token=auth-0e5aa1ddb3a2463a943ea5b58fc40eb3
meshingress.mcp.auth.stub.client-id=demo-client
meshingress.mcp.auth.stub.subject=demo-subject
