package dev.mrk.aegis;

/** Stable, credential-safe reasons suitable for callers and audit records. */
public enum DenialReason {
    INVALID_CREDENTIAL,
    EXPIRED_CREDENTIAL,
    UNSUPPORTED_CREDENTIAL,
    MISSING_REQUIRED_GRANT,
    AUTHENTICATION_REQUIRED,
    AUTHORIZATION_DENIED,
    CREDENTIAL_AUTHORIZATION_REQUIRED,
    BOOTSTRAP_DISABLED,
    BOOTSTRAP_INVALID_ACTION,
    BOOTSTRAP_INVALID_CREDENTIAL,
    BOOTSTRAP_CREDENTIAL_EXPIRED,
    BOOTSTRAP_CREDENTIAL_CONSUMED,
    BOOTSTRAP_CREDENTIAL_REVOKED,
    BOOTSTRAP_ATTEMPTS_EXHAUSTED,
    BOOTSTRAP_ADMINISTRATOR_EXISTS,
    BOOTSTRAP_PROFILE_NOT_ADMINISTRATOR,
    BOOTSTRAP_PROFILE_ALREADY_EXISTS
}
