<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.mrk.meshingress</groupId>
        <artifactId>meshingress</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>meshingress-tool-bundle</artifactId>
    <name>meshingress-tool-bundle</name>
    <description>Classpath tool dependency bundle for Meshingress server startup discovery</description>

    <repositories>
        <repository>
            <id>meshingress-artifacts</id>
            <url>file:${maven.multiModuleProjectDirectory}/repository/artifacts</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>dev.mrk.toolspace</groupId>
            <artifactId>helloworld</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>dev.mrk.toolspace</groupId>
            <artifactId>powershell-cli</artifactId>
            <version>${project.version}</version>
        </dependency>

    </dependencies>
</project>
