#Meshingress MCP WebSocket demo credentials
#Mon Jun 29 09:37:50 EDT 2026
meshingress.mcp.auth.stub.access-token=access-e92e8e55-29c1-4513-b7c1-e16f00e4ef42
meshingress.mcp.auth.stub.auth-token=auth-5559ade0-0b09-415c-8043-07bef733a201
meshingress.mcp.auth.stub.client-id=java-demo-client
meshingress.mcp.auth.stub.enabled=true
meshingress.mcp.auth.stub.secret-key=secret-ca94c773-4392-48c4-8681-859545ef40c6
meshingress.mcp.auth.stub.subject=java-demo-subject
