#Meshingress MCP WebSocket demo credentials
#Fri May 22 13:44:49 EDT 2026
meshingress.mcp.auth.stub.access-token=access-d405a7e9-73af-4668-800d-74dffce5bac6
meshingress.mcp.auth.stub.auth-token=auth-7d14312e-cf41-4296-97b8-31e297d2ce99
meshingress.mcp.auth.stub.client-id=java-demo-client
meshingress.mcp.auth.stub.enabled=true
meshingress.mcp.auth.stub.secret-key=secret-48570b91-4457-4919-9a32-c4612c5a2d76
meshingress.mcp.auth.stub.subject=java-demo-subject
