#Meshingress MCP WebSocket demo credentials
#Wed May 20 01:34:33 EDT 2026
meshingress.mcp.auth.stub.access-token=access-3856f1cf-17eb-4e0f-957a-4e4951c54fd0
meshingress.mcp.auth.stub.auth-token=auth-67955e05-2640-421a-802e-6ca0ab502232
meshingress.mcp.auth.stub.client-id=java-demo-client
meshingress.mcp.auth.stub.enabled=true
meshingress.mcp.auth.stub.secret-key=secret-39ce777e-96d9-4f15-bb24-e364e5854696
meshingress.mcp.auth.stub.subject=java-demo-subject
#Using generated security password: f9b883dc-cbf7-4c79-a7ed-11c1e5279c6b
