import type { DrawerView, LogEntry, WorkflowEdge, WorkflowNode, WorkflowRunResult } from '../types'
import { workflowDefinition } from '../definition'
import { Empty } from './ExplorerPanel'

export function WorkflowDrawer({ drawer, logs, lastRun, nodes, edges, onChange }: { drawer: DrawerView; logs: LogEntry[]; lastRun: WorkflowRunResult | null; nodes: WorkflowNode[]; edges: WorkflowEdge[]; onChange: (view: DrawerView) => void }) {
  const tabs: Array<{ id: DrawerView; label: string }> = [{ id: 'current', label: 'Current execution' }, { id: 'variables', label: 'Variables' }, { id: 'definition', label: 'Definition' }]
  return <section className="drawer"><div className="tabs">{tabs.map((tab) => <button className={`tab${drawer === tab.id ? ' active' : ''}`} key={tab.id} onClick={() => onChange(tab.id)} type="button">{tab.label}</button>)}</div><div className="drawer-body">{drawer === 'current' && (logs.length ? logs.map((log) => <div className="log-row" key={`${log.time}-${log.source}`}><span className="log-time">{log.time}</span><strong>{log.source}</strong><span>{log.message}</span></div>) : <Empty message="No current execution. Run the workflow to populate live logs." />)}{drawer === 'variables' && <Variables lastRun={lastRun} nodes={nodes} />}{drawer === 'definition' && <pre>{JSON.stringify(workflowDefinition(nodes, edges), null, 2)}</pre>}</div></section>
}

function Variables({ lastRun, nodes }: { lastRun: WorkflowRunResult | null; nodes: WorkflowNode[] }) { if (!lastRun) return <>{nodes.map((node) => <div className="log-row" key={node.id}><span className="log-time">object</span><strong>{node.output}</strong><span>{node.title} structured output</span></div>)}</>; const entries = Object.entries(lastRun.results ?? {}); return entries.length ? <>{entries.map(([name, value]) => <div className="box" key={name}><div className="section-heading">{name}</div><pre>{JSON.stringify(value, null, 2)}</pre></div>)}</> : <Empty message="This run produced no named results." /> }
